// Contexte: on est sur une API et une de nos ressources est une voiture
// On veut pouvoir créer une voiture, la modifier, la supprimer, la récupérer

interface Car {
  id: string;
  brand: string;
  power: number;
  model: string;
  color: string | undefined;
  analyticsId: string | undefined;
  createdAt: Date;
  updatedAt: Date;
}

// L'objectif du premier exercice dans un premier temps est de créer le type
// correspondant à la récupération de la marque de la voiture et de sa couleur à partir de l'id

// https://www.typescriptlang.org/play?#code/PTAEGEHsDsBcFMAeCBcoangZ1qLBXAJ1H2nlAEEAFASU11PIBNzpItRDstIiBjbJhwkyoAG6QAlrCLwAUCFAB5aOPj5cAB14TJxPoQCX8Yo3FSZXADSgANgENQAW0hNJAM0kmbDvPk2ahJJO3naORnz+hlyEcnKScCbu9gIQ9sQA3nKgoJJMaDhB0ADmANzZoABGhPbQ+XiwRWUV2gDuJmjQ+E6VJuU5Liy2BY0JzTl8kLaQhCNNoAA+IiyeZEz9oLX2tgCesJJ8WDT1hWOLy-Cr8OsVBvD2CEwUsGgAIg-wG-5MH08voO8EOUAL5xRQAGQA5JBKgAreB8fbuUBMfCgQLwJxeYhIEx8A7MWocUjorhYkygBBOTQcbC4FigAzGYi2ciwHaaeSKSaELhYbR1Wq4AAHYU4hkimmiD0kGAZvic6QAjvhmORfLpLOR4PTyFhHJN8KyiKBRZp0vtiPLIXkwWAobjCPjUnTKSYsdBDHYZlgVWzeAgOKzabz1IQOAAVADKeBguCMPFsqqwdtANFsoGSGlAhjE0gpTBtcEIrnwejVYtRmlsBxlcvIgUggUkhlghhTigjNCoaAAqvsa1h1Y4mJA+KBo+jeMRGjoKcGqjBiQPpPZyym5OzOWlCAAhGp1Ch1KDTYgAXga80UAE1p5SOeQABYmT5xBRgV5KUAAOSUEYnSi9uAAASoAAFpKN+ACi74QIIgawBwnKECEsAIHAKLkGI2x5POjiJhosrQHIrK4PYaDgOk+61E8x5TDMoAXlkOTVDRaAAERUOoxTwJAsDsVYtz0bMoDsZUSbwAJcjAuUJE6lUFFUQetFMCeDFMRUrF1BxABK8DQPYRr8YJEzCWgpArAk1zSUAA

type CarBrandAndColor = Pick<Car, "brand" | "color">;

// L'objectif du second exercice est de créer le type correspondant
// à la récupération de la totalité des propriétés de la voiture à partir de l'id sauf
// la date de création et la date de modification

// https://www.typescriptlang.org/play?#code/PTAEGEHsDsBcFMAeCBcoangZ1qLBXAJ1H2nlAEEAFASU11PIBNzpItRDstIiBjbJhwkyoAG6QAlrCLwAUCFAB5aOPj5cAB14TJxPoQCX8Yo3FSZXADSgANgENQAW0hNJAM0kmbDvPk2ahJJO3naORnz+hlyEcnKScCbu9gIQ9sQA3nKgoJJMaDhB0ADmANzZoABGhPbQ+XiwRWUV2gDuJmjQ+E6VJuU5Liy2BY0JzTl8kLaQhCNNoAA+IiyeZEz9oLX2tgCesJJ8WDT1hWOLy-Cr8OsVBvD2CEwUsGgAIg-wG-5MH08voO8EOUAL5xRQAGQA5JBKgAreB8fbuUBMfB4BEwJiYRAmPgHcjYXAsUAGYzEWzkWA7TTkSaELhYbR1WqwBRgAAHYU4hkimmiD0kGGJvlgkFg22khhRgkCkECkkMsEMHGFjl0lnInM06X2xGFkLyeHs+HcbK5PwQ0pJRgFGHguF8FuY5EGHgOtugYLAEMhSFx+KEuAQhCcCSl00IWAAjvhKbwEBwKRwTFwiBwACoAZTwMFwRh4tljWC9oBotlAyQ0oEMYmkJhRBrghFc+D0zvN-ls7v2QvIsvliuVZvTNCoaAAqvsu1hyI7IHxQFnQNoiKBGjp60mqjAOBpJF3xW3i3IqTS0oQAOrSAAW8cBggAvA0mqVQIoAJq8Yin8jXkzyEtXiUUAADklHTRclHHcAAAlQAALSUECAFEzXAQQE1gDgaRDe0EDgK0xAlFhyUcAs9xgOQKVwew0HAdIr1gW8NHvDgnyyHI8jQAAiABmbirAqapanqbiqHUYp4DFATbimGYeMqQt4BknI2g6UAACZeIANkEnItl2fZDmOHiAEYtIAFhU5xXHgYZQG4jSAAZtJk4Fyio+0qjohibzvD42NADjclEjTrOEuoeIAJXgaBjVsWBrMmCM0FIFYEmuPTl0gdpZlACyAFZdIqAy9gOI5RPM3irKywY7J4izwTcoA

type CarWithoutDates = Omit<Car, "createdAt" | "updatedAt">;

// L'objectif du troisième exercice est de créer le type correspondant à la récupération des données mais
// comme c'est une lecture, on ne veut pas que ces propriétés soient modifiables

// https://www.typescriptlang.org/play?#code/PTAEGEHsDsBcFMAeCBcoangZ1qLBXAJ1H2nlAEEAFASU11PIBNzpItRDstIiBjbJhwkyoAG6QAlrCLwAUCFAB5aOPj5cAB14TJxPoQCX8Yo3FSZXADSgANgENQAW0hNJAM0kmbDvPk2ahJJO3naORnz+hlyEcnKScCbu9gIQ9sQA3nKgoJJMaDhB0ADmANzZoABGhPbQ+XiwRWUV2gDuJmjQ+E6VJuU5Liy2BY0JzTl8kLaQhCNNoAA+IiyeZEz9oLX2tgCesJJ8WDT1hWOLy-Cr8OsVBvD2CEwUsGgAIg-wG-5MH08voO8EOUAL5xRQAGQA5JBKgAreB8fbuUBMfCgRpSLCSAAXIUwiBMfAO5GwuBYoAMxmItnIsB2mnIk0IXCw2jqtVwAAOwpxDJFNNEHpIMCwOEwYNBjBwABTwVRIPi2fAckiaH6PZ70ClcX7PACUznskiwCjAkyceL4kNJInINMRshsGFEYnUWnsHAAjvhGYJApBApJDLBDBweF44M5XB5JPZKjSTRDHO4YIjhapyQhhOLpJtdNTrcz1MQCPoABb2b2MitOTSgABE4FqbFwHqxxVUsEgoAAdH2qgj7PgsORc8bNpx7kwALQwXagf0Mwh0nv1uJ0hlpQgAdWkZd4sEBggAvMonNIADxNwg2et3XWwevnevfB-1gB85TkG-I14ASlOoCngB9jitAuxXuku6wPuGhHlgn6gIoACavDED+oBliY8hgmArxKKAABySgACqgCRSgAKrgAAEqAABaSiEQAoqaECCFmsAcEuISwAgkbkmI2x5CYPI8Eq+wwHEkzQMIozYCRkDgBWJTwNeQGgNKfDpGg-5Tgax7vqAWQTOkPZ5Bp9ZkK0ABq2w+vWGzaYQPbVLUTCWdZdlKvAjm3GZbSiaeACMABMADMTlmYM8C2J58C2fZvlRS5kzTMQp5WQl3kOSlPZbLs+yHMc8WJT5fnAkAA

type CarRead = Readonly<CarWithoutDates>;

// L'objectif de la quatrière partie est de créer le type correspondant à la mise à jour d'une voiture
// Tous les champs peuvent être mis à jour sauf l'id, la date de création et la date de modification
// et peuvent être mis à jour sans préciser tous les champs

type CarUpdate = Partial<Omit<Car, "id" | "createdAt" | "updatedAt">>;

// On se place dans le contexte où on veut mettre une valeur par défaut pour tous les champs de la voiture de base
// Créer le type correspondant

type CarWithDefaults = Required<Car>;

// On a une liste de marque de voiture et on veut créer le type associé avec toutes les marques et leurs propriétés

type CarBrands =
  | "Renault"
  | "Peugeot"
  | "Toyota"
  | "Volkswagen"
  | "Skoda"
  | "Citroën"
  | "Fiat"
  | "Mini"
  | "Honda"
  | "Nissan";

interface BrandInfo {
  id: string;
  creationDate: Date;
  originCountry: string;
}

type CarBrandsWithProperties = Record<CarBrands, BrandInfo>;

// On ne veut que les marques qui ne sont pas japonaises

type CarBrandsJapanese = Extract<CarBrands, "Toyota" | "Honda" | "Nissan">;

type CarBrandsWithoutJapanese = Exclude<
  CarBrands,
  "Toyota" | "Honda" | "Nissan"
>;


// https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHsoFs5kgEwBFcUBvAKGWXxIC5kBnMKUAcwG5yBfc80SWIhTFIASQDKAeWQUqNSPRABXLACNonHrwToQTZKqXAANvgAywJpJgZsuAiIgNkAXmQAKeU-rvHEyQA+tjh4EEQkAJQA2gC6yBGuAHwylNQkDAB0MJgAoogAFu6ekUkpVFTAMB5gAJ4ADhDoVV4ZXq4ubgBETCwgrJ0JsuVUUBBgSlAgaZCtJKlUPMOj45PI2XZgjsUzXhGcCxHc5AD0x8iSUwBuEEpgyDp6zEajyMZwr5aQ1E5rwAj5wGgzjqcGwwHuYy+xk+KBOZwAwmNkBAAB7QBB-FD8KDofBGO7GFAgUE4gDubAANPcAOROAm0lHIACMjAmrx+tQayFYSlB+AYvFOyAAKsA6vR8ng6gxaKdSfKMpynAgWHUwG8+hlMKxjvh0AgGMd8nAQPhVOh0ABrY4AJmOxKgZLYGUlWGMAGIlAw2ABaJU+uqjfB-dLaXT6GAmCAABVw+WcbhJcBq1lQwCgTAAgqbxBAHvgsiYBO5Uu5IxmwJIoLn8wkXMly1Zq3ndAX+NB4EhhfUUABCDrITqNsCdcgRDI4OolqhCgDqKGN12QJuQlgYSgX0BQwvE1HQPxA6DuSlNQLAJvwyDAxruwBwrAgpfJ19E94gdeSz-yr7gD4yd9-CBUCUYxjFja8MlUOAGBjONkAAakHY5OgQ5Avx-P8AIfYDQPA-JC0JAA5OAsEfQ5BTOcR0GMW5gF0CjkEIo9vGQMNHl+Qk8IYG1XGXR1k1TdMsxzFtTQI4tS2HKsa1bCJ6Ck5t81XZxZ2AF831KBSZLE9tBC7HtkH7Lph1HcdJ2nDx0LfD80LU7833-N8cLAuNIOg2Dr1QzpkNQqzAMcwDnLwgiIGI0ix3IIA
// https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJIFs4HMUG8BQyyARnAM4QAKcYAFgFzJlhShYDchyMwANhADk46CI2asQHfAF98+UJFiIUAdWB0M2PFwXR4SACoBPAA6jkAIh5RmFzkWCYcAMQCuvXtTqNNOTrPlwPWVkNToAe1cwX20HIKVDU3MLCgRwkAATOxk5fDSQZmQ4KCg4IwB5GGdgGzAAQUyAZQh8jMYACjDaGIAfLsjopwgASgBtAF0AXmQJznwAennkcpBkADcIKOR88VcalF44ZF5gZhQMiDJuYARaYGgrk2L0YG2IMEhj08+FpZXkBRQcIZPZgY4oU4AhDAAA0b2QAEc9usjq5VghSqsTLxXFdeOFQExXFBwcgQMUgQB3Nhw9LICBYzZg7G4pibfgicDIKJ8U7QZBgJLhGByRbIAzAEyMWgfExkeiLSlKgB0grMZAxkrAh0kyvCUCw8wy4QQZHmtDgmWI4XCAGt5gAmebkkrham6mXoXgAYlxbAAtGqIP6TFAIBkbjRLnIdmCePwvLQrtMKWVKtVag0Ms1Wsr44p2lx2tZmOUoDn0hlhshJgA+a61MsVzLK3QJCDGMzIACEk2mVhqtnww2VmBMhaIYpUKAtGyKq1OZFcM+gKAMjWQxsuZPCYLRF1qloyAotYMcWiL1I0Q2rdeQV+6Q1bQzcHkTytIFETyAA1JZ5hYv73uoj5aM+Wivp4NC0HmfCCMIEDDrkYqNOEOJgMA6QxukhTxlQ0FkA6NZFCUaZVIO9RNC0lawbwBZFiWYBNtRmTDIwjHMa0AJXF0MQ1vWHHlixGStvE+gdkkPZ9pYjEWMOo5wOOl4gTEt71g+MTgS47hQXQH7kPhdBARYAFARpT7ntpb7QbR8EiEhQA
// https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJIFs4HMUG8BQyyARnAM4QAKcYAFgFzJlhShYDchyMwANhADk46CI2asQHfAF98+UJFiIUAdWB0M2PF2CYcAMQCuvXtTqNNOTrPnho8JMjV0A9obCXtRF3WgBBMBZgYndRJiDJazl+MCYXETo2FQgAcQgwfSh4vxA-AAdgRkMQAGsQFwB3EE58BBcQZmQWOAaYFyh0TOyC5ABeZAAKPLgoYSLS8qqASj6APmQCImAYQdpyTyGR4SmZxaJkKHTDKBASQz4AEzNaTdH0Kc4iWSJDsGPTgHIPmTk6hti1mRPH1BjNevNihcIDwQBALjU-o0QpdriCBrotIxnLRPGD5hicAA6AkQIwma6E0gUVEAamQACIAPT05B0knEvSk4ymGi0Qk8fhCEQ1fCMxnIADKLl47mA9TkYuQtECeTI9DFxF4LiwhN8LguLkJdXQjIATAAGU2mxnmgCMjLAAE88hAyAhWHkwABaQ55XjKL3kL1Ol1YQwjC5kRmi8US3R+5bAaDIfjIBDkZB5NxQZCwzMZuAANxcwBzxSazogYYjuddYAAlzHkABVMB8YAUHMAeWIACsIAgwIS8lkwD5K0a4CY0-FiKB68giwOUygQxAXCs-e4AC+xACOhhQqfTzDYyAgp2xnibKQjyf9uZ8ctOUIrLuQ1agF1rzAXWeOKYfBAAAe0AIMAjgXB8cAjgAF2QTYAKLAQmB7Jv+UAHiWK7IKAtaZhA7j5mQyAAFcsCgsq8B2ja-PUjSAp4pposMdzjGUlQgFMjCscIuEkVenJzMgPb9oOw6juOLqEoCXZVJQWQulATqTiYtzCAANAyJJkjydD0jMABkhmDLx6CLgJ6g4pyUwcloumogAhL0-SQtCoBwuwQA